const COURSE_TITLE_TEXT_MIN_LIMIT: number = 10;
const COURSE_TITLE_TEXT_MAX_LIMIT: number = 70;
const COURSE_SECTION_TITLE_LIMIT: number = 70;
const COURSE_SECTION_DESCRIPTION_LIMIT: number = 100;
const COURSE_LECTURE_TITLE_LIMIT: number = 70;
const COURSE_KEYWORD_TEXT_LIMIT: number = 15;
const COURSE_REVIEW_NOTE_TEXT_LIMIT: number = 450;
const COURSE_KEYWORDS_MAX_LENGTH: number = 40;
const COURSE_KEYWORDS_MAX_COUNT: number = 20;
const COUPON_CODE_MIN_LIMIT: number = 10;
const COUPON_CODE_MAX_LIMIT: number = 35;
const COUPON_CODE_MONTH_LIMIT: number = 6;
const REPORT_TITLE_TEXT_MIN_LIMIT: number = 4;
const REPORT_TITLE_TEXT_MAX_LIMIT: number = 70;
const REPORT_DESCRIPTION_TEXT_MIN_LIMIT: number = 50;
const REPORT_DESCRIPTION_TEXT_MAX_LIMIT: number = 1000;
const NAME_MIN_TEXT_LIMIT: number = 2;
const NAME_MAX_TEXT_LIMIT: number = 100;

export {
  COURSE_TITLE_TEXT_MIN_LIMIT,
  COURSE_TITLE_TEXT_MAX_LIMIT,
  COURSE_SECTION_TITLE_LIMIT,
  COURSE_SECTION_DESCRIPTION_LIMIT,
  COURSE_LECTURE_TITLE_LIMIT,
  COURSE_KEYWORD_TEXT_LIMIT,
  COURSE_REVIEW_NOTE_TEXT_LIMIT,
  COURSE_KEYWORDS_MAX_LENGTH,
  COURSE_KEYWORDS_MAX_COUNT,
  COUPON_CODE_MIN_LIMIT,
  COUPON_CODE_MAX_LIMIT,
  COUPON_CODE_MONTH_LIMIT,
  REPORT_TITLE_TEXT_MIN_LIMIT,
  REPORT_TITLE_TEXT_MAX_LIMIT,
  REPORT_DESCRIPTION_TEXT_MIN_LIMIT,
  REPORT_DESCRIPTION_TEXT_MAX_LIMIT,
  NAME_MIN_TEXT_LIMIT,
  NAME_MAX_TEXT_LIMIT,
};
